# Assignment #03
1. Explore College Scorecard website - https://collegescorecard.ed.gov/ 

2. Explore College Scorecard Data web page - https://collegescorecard.ed.gov/data/

3. Download and skim the documentation - https://collegescorecard.ed.gov/assets/FullDataDocumentation.pdf

4. Download the dataset - https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data.zip (265MB Zip File)

5. Unzip the file into a folder (there are many files, one for each school year)

6. Import the 2017-2018 school year file "MERGED2017_18_PP.csv" and explore:   

    * how many colleges or rows?   

    * how many variables or columns?   

    * Look at the first 20 rows   

    * look at the last 20 rows   

    * Look at a random sample of 20 rows    

7. Since there are too many variables to explore, many of which are not interesting. Modify your import statement to only import the following 9 variables:

- UNITID
- INSTNM
- CITY
- STABBR
- ZIP
- ADM_RATE
- UGDS
- TUITIONFEE_IN
- MN_EARN_WNE_P10 

8. Download and read the data dictionary file - https://collegescorecard.ed.gov/assets/CollegeScorecardDataDictionary.xlsx

Find out the definition of the above 9 variables and document the definitions in the Jupyter Notebook so that the readers will not need to repeat what you have done to know the meaning of these variables.

9. Use the predefined cells below to conduct and document your data exploration.

When in doubt, Google. Find examples and read documents/tutorials. 

Have fun!

In [1]:
# Import libraries
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# load the 2017-2018 school year file "MERGED2017_18_PP.csv"   
data= pd.read_csv(r"C:\Users\rahma\OneDrive\Documents\Monty Documents\Data 690 Stats\Assignment 3\MERGED2017_18_PP.csv")
data.columns
# data[['UNITED', 'INSTNM', 'CITY', 'STABBR', 'ZIP', 'ADM_RATE', 'UGDS', 'TUITIONFEE_IN', 'MN_EARN_WNE_P10']]

C:\Users\rahma\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (31,1726,1727,1728,1729,1815,1817,1823,1830,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Index(['UNITID', 'OPEID', 'OPEID6', 'INSTNM', 'CITY', 'STABBR', 'ZIP',
       'ACCREDAGENCY', 'INSTURL', 'NPCURL',
       ...
       'OMAWDP8_NOTFIRSTTIME_POOLED_SUPP', 'OMENRUP_NOTFIRSTTIME_POOLED_SUPP',
       'OMENRYP_FULLTIME_POOLED_SUPP', 'OMENRAP_FULLTIME_POOLED_SUPP',
       'OMAWDP8_FULLTIME_POOLED_SUPP', 'OMENRUP_FULLTIME_POOLED_SUPP',
       'OMENRYP_PARTTIME_POOLED_SUPP', 'OMENRAP_PARTTIME_POOLED_SUPP',
       'OMAWDP8_PARTTIME_POOLED_SUPP', 'OMENRUP_PARTTIME_POOLED_SUPP'],
      dtype='object', length=1977)

In [3]:
# Find out how many colleges or rows?   
# Find out how many variables or columns? 

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7112 entries, 0 to 7111
Columns: 1977 entries, UNITID to OMENRUP_PARTTIME_POOLED_SUPP
dtypes: float64(1862), int64(14), object(101)
memory usage: 107.3+ MB

In [4]:
# Look at the first 20 rows  
data.head(20)

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMAWDP8_NOTFIRSTTIME_POOLED_SUPP,OMENRUP_NOTFIRSTTIME_POOLED_SUPP,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,https://galileo.aamu.edu/NetPriceCalculator/np...,...,0.4048,0.2645,0.0137,0.315,0.3755,0.2958,0.0289,0.4224,0.2635,0.2852
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,www.uab.edu,uab.studentaidcalculator.com/survey.aspx,...,0.5448,0.12,0.0728,0.2583,0.5872,0.0817,0.1398,0.2618,0.3977,0.2008
2,100690,2503400,25034,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,...,0.4647,0.1912,0.0148,0.3284,0.4391,0.2177,0.028,0.3645,0.4486,0.1589
3,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu,finaid.uah.edu/,...,0.5121,0.1593,0.0165,0.323,0.5361,0.1243,0.0245,0.3947,0.3476,0.2331
4,100724,100500,1005,Alabama State University,Montgomery,AL,36104-0271,Southern Association of Colleges and Schools C...,www.alasu.edu,www.alasu.edu/cost-aid/forms/calculator/index....,...,0.4226,0.0754,0.0254,0.5327,0.3133,0.1286,0.021,0.5804,0.1678,0.2308
5,100751,105100,1051,The University of Alabama,Tuscaloosa,AL,35487-0166,Southern Association of Colleges and Schools C...,www.ua.edu/,financialaid.ua.edu/net-price-calculator/,...,0.6376,0.1267,0.0073,0.2431,0.6817,0.0679,0.0142,0.2842,0.4599,0.2416
6,100760,100700,1007,Central Alabama Community College,Alexander City,AL,35010,Southern Association of Colleges and Schools C...,www.cacc.edu,https://www.cacc.edu/net-price-calculator/,...,0.2807,0.3502,0.0142,0.3794,0.2206,0.3858,0.0092,0.3258,0.2769,0.3881
7,100812,100800,1008,Athens State University,Athens,AL,35611,Southern Association of Colleges and Schools C...,www.athens.edu,https://24.athens.edu/apex/prod8/f?p=174:1:394...,...,0.5627,0.2276,0.0109,0.1797,0.649,0.1604,0.0181,0.2112,0.4741,0.2966
8,100830,831000,8310,Auburn University at Montgomery,Montgomery,AL,36117-3596,Southern Association of Colleges and Schools C...,www.aum.edu,www.aum.edu/current-students/financial-informa...,...,0.4884,0.2048,0.0134,0.4208,0.327,0.2388,0.0289,0.3737,0.2352,0.3622
9,100858,100900,1009,Auburn University,Auburn,AL,36849,Southern Association of Colleges and Schools C...,www.auburn.edu,https://www.auburn.edu/admissions/costcalc/fre...,...,0.7038,0.072,0.0062,0.2026,0.7405,0.0506,0.0143,0.3829,0.4571,0.1457
10,100937,101200,1012,Birmingham Southern College,Birmingham,AL,35254,Southern Association of Colleges and Schools C...,www.bsc.edu/,www.bsc.edu/fp/np-calculator.cfm,...,0.6196,0.0326,0.0031,0.3303,0.6319,0.0348,NaN,NaN,NaN,NaN
11,101028,1218200,12182,Chattahoochee Valley Community College,Phenix City,AL,36869,Southern Association of Colleges and Schools C...,www.cv.edu,www.cv.edu/about/consumer-information/,...,0.2463,0.1667,0.0155,0.5959,0.2216,0.167,0.0067,0.5705,0.1678,0.255
12,101073,1055400,10554,Concordia College Alabama,Selma,AL,36701,NaN,www.ccal.edu/,www.ccal.edu/admissions/net-pricing-calculator/,...,0.0957,0.505,0.006,0.2376,0.1037,0.6526,0,0.2075,0.0094,0.783
13,101116,1303906,13039,South University-Montgomery,Montgomery,AL,36116,Southern Association of Colleges and Schools C...,www.southuniversity.edu/montgomery#location=Mo...,www.southuniversity.edu/montgomery/net-price-c...,...,0.2574,0.6426,0,0.1263,0.2184,0.6553,0.0035,0.0804,0.2308,0.6853
14,101143,101500,1015,Enterprise State Community College,Enterprise,AL,36330-1300,Southern Association of Colleges and Schools C...,www.escc.edu,https://www.escc.edu/netprice/npcalc.htm,...,0.283,0.3396,0.0095,0.3663,0.3104,0.3138,0.004,0.4113,0.1707,0.414
15,101161,106000,1060,Coastal Alabama Community College,Bay Minette,AL,36507-2698,Southern Association of Colleges and Schools C...,www.coastalalabama.edu,www.coastalalabama.edu,...,0.297,0.0998,0.0119,0.5981,0.2845,0.1056,0.019,0.5704,0.2838,0.1268
16,101189,100300,1003,Faulkner University,Montgomery,AL,36109-3390,Southern Association of Colleges and Schools C...,www.faulkner.edu,www.faulkner.edu/net-price-calculator-form/,...,0.5333,0.1701,0.0057,0.3406,0.4638,0.19,0.0112,0.3825,0.3582,0.2481
17,101240,101700,1017,Gadsden State Community College,Gadsden,AL,35903,Southern Association of Colleges and Schools C...,www.gadsdenstate.edu,www.gadsdenstate.edu/net-price-calculator,...,0.2818,0.5138,0.0215,0.1641,0.2742,0.5402,0.0835,0.1191,0.2338,0.5636
18,101277,4187200,41872,New Beginning College of Cosmetology,Albertville,AL,35951,National Accrediting Commission of Career Arts...,www.nbccosmetology.com,nbccosmetology.com/sa/nbc_zonemap/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,101286,101800,1018,George C Wallace Community College-Dothan,Dothan,AL,36303-9234,Southern Association of Colleges and Schools C...,www.wallace.edu,www.wallace.edu/net_price_calculator.aspx,...,0.3583,0.294,0.0221,0.2986,0.2993,0.3799,0.043,0.2557,0.2743,0.427

In [5]:
# Look at the last 20 rows 
data.tail(20)

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMAWDP8_NOTFIRSTTIME_POOLED_SUPP,OMENRUP_NOTFIRSTTIME_POOLED_SUPP,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP
7092,47503311,4208611,42086,Relay Graduate School of Education - San Antonio,San Antonio,TX,782155155,Middle States Commission on Higher Education,relay.edu/location/relay-san-antonio,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7093,47503312,4208612,42086,Relay Graduate School of Education - Dallas-Fo...,Dallas,TX,752075155,Middle States Commission on Higher Education,relay.edu/location/relay-dallas-fort-worth,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7094,47503313,4208613,42086,Relay Graduate School of Education - Washingto...,Washington,DC,200375155,Middle States Commission on Higher Education,relay.edu/location/relay-washington-dc,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7095,47647001,4088301,40883,WestMed College - Merced,Merced,CA,953400000,NaN,www.westmedcollege.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7096,47662901,4189101,41891,Salon Institute - Columbus Campus,Lewis Center,OH,430359153,National Accrediting Commission of Career Arts...,www.saloninstitute.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7097,47691101,4205801,42058,SAE Institute of Technology San Francisco,Emeryville,CA,94608,NaN,usa.sae.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7098,48065701,869423,8694,Rasmussen College - Overland Park,Overland Park,KS,662102786,Higher Learning Commission,rasmussen.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7099,48079001,4218901,42189,Rocky Vista University - Southern Utah,Ivins,UT,847386756,Higher Learning Commission,www.rvu.edu/rvu-su/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7100,48092101,4220001,42200,Designer Barber & Stylist School -,Springdale,AR,727620990,National Accrediting Commission of Career Arts...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7101,48133101,4213501,42135,Sharp Edgez Barber Institute - Buffalo,Buffalo,NY,142170000,Council on Occupational Education,www.sharpedgezbarberinstitute.com,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7102,48154401,4220901,42209,National Personal Training Institute of Cleveland,Highland Heights,OH,44143,Accrediting Council for Continuing Education &...,nptiohio.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7103,48305401,4224601,42246,Barber School of Pittsburgh - Ambridge,Ambridge,PA,150030000,NaN,www.bsp.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7104,48312401,108131,1081,Arizona State University at Tucson,Tucson,AZ,857454284,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7105,48312402,108161,1081,Arizona State University - ASU Colleges at Lak...,Lake Havasu City,AZ,864036877,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7106,48312403,108162,1081,Arizona State University at The Gila Valley,Thatcher,AZ,855525545,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7107,48312404,108163,1081,Arizona State University at Yuma,Yuma,AZ,853656900,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7108,48387801,4223701,42237,Bay Area Medical Academy - San Jose Satellite ...,San Jose,CA,95113,Accrediting Council for Independent Colleges a...,www.bamasf.com/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7109,48400201,4228101,42281,High Desert Medical College,Lancaster,CA,935340000,Accrediting Council for Continuing Education &...,www.hdmc.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7110,48778201,4221501,42215,BCI - Malden,Malden,MA,021480000,NaN,bostoncareer.org,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7111,49005401,4182601,41826,Health Career Institute- Lauderdale Lakes,Lauderdale Lakes,FL,333137268,Accrediting Commission of Career Schools and C...,www.hci.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Look at a random sample of 20 rows  

random2 = data.sample(n=20)
random2

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMAWDP8_NOTFIRSTTIME_POOLED_SUPP,OMENRUP_NOTFIRSTTIME_POOLED_SUPP,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP
3219,217891,492300,4923,Clinton College,Rock Hill,SC,29730,Transnational Association of Christian College...,www.clintoncollege.edu,www.clintoncollege.edu/studentaffairs.htm,...,0.0854,0.9146,0,0.0743,0.401,0.5248,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
60,102580,884300,8843,Alaska Bible College,Palmer,AK,99645,Association for Bibical Higher Educaiton,www.akbible.edu/,www.akbible.edu/admissions/tuition-aid/net-pri...,...,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
1304,156620,196300,1963,Eastern Kentucky University,Richmond,KY,40475-3102,Southern Association of Colleges and Schools C...,www.eku.edu,finaid.eku.edu,...,0.5382,0.2049,0.0102,0.2989,0.4825,0.2084,0.0189,0.2928,0.3387,0.3495
5233,448585,405719,4057,National American University-Zona Rosa,Kansas City,MO,64153-1934,NaN,www.national.edu/locations/campuses/zona-rosa/,www.national.edu/net-price-calculator/,...,0.2544,0.7422,0,0,0.2245,0.7755,0.0018,0,0.1613,0.8369
5162,447050,4005300,40053,United States University,San Diego,CA,92108,Western Association of Schools and Colleges Se...,https://www.usuniversity.edu/,https://www.usuniversity.edu/net-price-calcula...,...,0.8302,0.1132,0,0.0714,0.4857,0.4429,NaN,NaN,NaN,NaN
5479,455080,4145700,41457,Paul Mitchell the School-Springfield,Springfield,MO,65807,National Accrediting Commission of Career Arts...,springfield.paulmitchell.edu,springfield.paulmitchell.edu/financial-aid/tui...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5339,450696,974803,9748,Carrington College-Stockton,Stockton,CA,95207,Western Association of Schools and Colleges Ac...,https://carrington.edu/,https://carrington.edu/financial-aid/how-much-...,...,0.7541,0.1176,0,0.1342,0.7197,0.1461,NaN,NaN,NaN,NaN
6260,483665,4184300,41843,Paul Mitchell the School-Ardmore,Ardmore,OK,73401-3912,National Accrediting Commission of Career Arts...,paulmitchell.edu/ardmore/,paulmitchell.edu/ardmore/programs/cosmetology,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
558,127617,998100,9981,Morgan Community College,Fort Morgan,CO,80701,Higher Learning Commission,https://www.morgancc.edu,https://www.morgancc.edu/npc/npcalc.htm,...,0.4317,0.1583,0.0254,0.2234,0.4365,0.3147,0.0312,0.2495,0.3742,0.3451
343,117168,2330500,23305,Laguna College of Art and Design,Laguna Beach,CA,92651,Western Association of Schools and Colleges Se...,www.lcad.edu,https://www.lcad.edu/admissions/tuition-financ...,...,0.463,0.537,0,0,0.5611,0.4389,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
6131,481164,4207600,42076,American Academy of Personal Training,New York,NY,10013,NaN,www.aapt.edu,www.aapt.edu/npcalc.htm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5462,454908,4143100,41431,Professional Hands Institute,Miami,FL,33125,NaN,www.prohands.edu,www.prohands.edu,...,PrivacySuppressed,PrivacySuppressed,0,0.0352,0.8121,0.1526,NaN,NaN,NaN,NaN
3223,217961,343100,3431,Converse College,Spartanburg,SC,29302-0006,Southern Association of Colleges and Schools C...,www.converse.edu/,www.converse.edu/admissions/financial-aid-and-...,...,0.6923,0.3077,0,0,0.5886,0.4114,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
2127,186283,262800,2628,Rider University,Lawrenceville,NJ,08648-3099,Middle States Commission on Higher Education,www.rider.edu,https://www.rider.edu/netpricecalculator/,...,0.7134,0.1038,0.0012,0.2734,0.6707,0.0547,0.009,0.1973,0.5516,0.2422
2590,199971,3570300,35703,Carolina Christian College,Winston Salem,NC,27105,Association for Bibical Higher Educaiton,www.carolina.edu,www.carolina.edu/npcalc_000.htm,...,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,NaN,NaN,NaN,NaN
3407,223117,2331200,23312,Baptist Missionary Association Theological Sem...,Jacksonville,TX,75766-5407,Southern Association of Colleges and Schools C...,www.bmats.edu,www.bmats.edu,...,0.3548,0.6129,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed
2349,193858,1055100,10551,New York School for Medical and Dental Assistants,Long Island City,NY,11101,Accrediting Commission of Career Schools and C...,nysmda.com,nysmda.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4513,417248,2245300,22453,Howell Cheney THS/CT Aero Tech School,Hartford,CT,06114,Council on Occupational Education,ctaero.cttech.org/,www.cttech.org/fa/amt/index.htm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2387,195216,282900,2829,St Lawrence University,Canton,NY,13617,Middle States Commission on Higher Education,www.stlawu.edu,https://www.stlawu.edu/financialaid/net-price-...,...,0.8,0.0462,0,0.1262,0.8563,0.0175,NaN,NaN,NaN,NaN
6485,487773,4220500,42205,Butte County Regional Occupational Program,Chico,CA,95928-7191,Council on Occupational Education,ctec.bcoe.org,bcoeregional.ss3.sharpschool.com/UserFiles/Ser...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Read (with naked eyes, not computer) the dictionary and find out the definitions of the following 12 columns and copy the text next to the column name
- UNITID: (definition here)  united          
- INSTNM:          institution name
- CITY:             city         
- ZIP:             zip code  
- ADM_RATE:    admission rate       
- UGDS:          undergraduate students    
- TUITIONFEE_IN:      tuition fee    
- MN_EARN_WNE_P10:    minimum earned

In [7]:
# reimport the data with above 12 columns (ignore all other variables)
data3= data[['UNITID', 'CITY', 'INSTNM', 'ZIP', 'ADM_RATE', 'UGDS', 'TUITIONFEE_IN', 'MN_EARN_WNE_P10']]
data3

,UNITID,CITY,INSTNM,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
0,100654,Normal,Alabama A & M University,35762,0.9027,4824.0,9857.0,NaN
1,100663,Birmingham,University of Alabama at Birmingham,35294-0110,0.9181,12866.0,8328.0,NaN
2,100690,Montgomery,Amridge University,36117-3553,NaN,322.0,6900.0,NaN
3,100706,Huntsville,University of Alabama in Huntsville,35899,0.8123,6917.0,10280.0,NaN
4,100724,Montgomery,Alabama State University,36104-0271,0.9787,4189.0,11068.0,NaN
...,...,...,...,...,...,...,...,...
7107,48312404,Yuma,Arizona State University at Yuma,853656900,NaN,NaN,NaN,NaN
7108,48387801,San Jose,Bay Area Medical Academy - San Jose Satellite ...,95113,NaN,NaN,NaN,NaN
7109,48400201,Lancaster,High Desert Medical College,935340000,NaN,NaN,NaN,NaN
7110,48778201,Malden,BCI - Malden,021480000,NaN,NaN,NaN,NaN
7111,49005401,Lauderdale Lakes,Health Career Institute- Lauderdale Lakes,333137268,NaN,NaN,22575.0,NaN

In [8]:

data2 = data3[data3["ADM_RATE"]!=0]
data2.shape

(7108, 8)

In [9]:
# Find out the 10 colleges that are hardest to get in (top 10)
data_ADM = data2.nsmallest(10, 'ADM_RATE')
data_ADM

,UNITID,CITY,INSTNM,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
2978,211893,Philadelphia,Curtis Institute of Music,19103,0.0330,131.0,2675.0,NaN
3979,243744,Stanford,Stanford University,94305,0.0473,7056.0,49617.0,NaN
1557,166027,Cambridge,Harvard University,02138,0.0516,7532.0,48949.0,NaN
2302,192110,New York,The Juilliard School,10023-6588,0.0592,486.0,43170.0,NaN
2123,186131,Princeton,Princeton University,08544-0070,0.0641,5246.0,47140.0,NaN
2233,190150,New York,Columbia University in the City of New York,10027,0.0661,8170.0,57208.0,NaN
633,130794,New Haven,Yale University,06520,0.0693,5742.0,51400.0,NaN
1575,166683,Cambridge,Massachusetts Institute of Technology,02139-4307,0.0717,4489.0,49892.0,NaN
212,110404,Pasadena,California Institute of Technology,91125,0.0774,961.0,49908.0,NaN
427,121345,Claremont,Pomona College,91711-6319,0.0836,1567.0,51075.0,NaN

In [10]:
# 10. Find out the average in-state tuition of top 10
mean = data_ADM["TUITIONFEE_IN"].mean()
print(mean)

45103.4

In [11]:
# Find out the average earnings of graduates from the top 10
mean3 = data_ADM["TUITIONFEE_IN"].mean()
print(mean3)

45103.4

In [12]:
# Find out the 10 colleges that are easiest to get in (bottom 10)
data_easy = data2.nlargest(10, 'ADM_RATE')
data_easy

,UNITID,CITY,INSTNM,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
24,101453,Florence,Heritage Christian University,35630-9977,1.0,59.0,11232.0,NaN
240,110918,Fresno,California Christian College,93727,1.0,16.0,9330.0,NaN
370,118161,Santa Rosa,Lytles Redwood Empire Beauty College Inc,95403,1.0,158.0,NaN,NaN
472,123280,Redding,Shasta Bible College and Graduate School,96002,1.0,42.0,12060.0,NaN
559,127653,Boulder,Naropa University,80302-6697,1.0,384.0,31790.0,NaN
571,127954,Boulder,Montessori Education Center of the Rockies,80301,1.0,16.0,NaN,NaN
652,131830,Washington,National Conservatory of Dramatic Arts,20007,1.0,32.0,9900.0,NaN
665,132842,Miami,Carlos Albizu University-Miami,33172-2209,1.0,236.0,12444.0,NaN
887,142090,Boise,Boise Bible College,83714-1220,1.0,128.0,12080.0,NaN
1011,147165,Peoria,Midstate College,61614-3595,1.0,274.0,16230.0,NaN

In [13]:
# Find out the average in-state tuition of the bottom 10
mean_2= data_easy["TUITIONFEE_IN"].mean()
print(mean_2)

14383.25

In [17]:
# Find out the average earnings of graduates from the bottom 10
data_easy["MN_EARN_WNE_P10"] = data_easy["MN_EARN_WNE_P10"].fillna(0)
mean4 = data_easy["MN_EARN_WNE_P10"]
print(mean4)

24      0.0
240     0.0
370     0.0
472     0.0
559     0.0
571     0.0
652     0.0
665     0.0
887     0.0
1011    0.0
Name: MN_EARN_WNE_P10, dtype: float64